name: flutter_movie_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  carousel_slider: ^4.2.1
  flutter_sticky_widgets: ^0.0.3
  shimmer: ^3.0.0

  # Navigation
  auto_route: ^7.8.4

  # Serialization
  json_annotation: ^4.8.1
  equatable: ^2.0.5

  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3

  # Dependency Injection
  get_it: ^7.6.4

  # Network
  http: ^1.1.2

  # Localizations
  easy_localization: ^3.0.0

  # Cache
  shared_preferences: ^2.2.2

  # Utils
  envied: ^0.5.2
  kartal: ^3.5.0
  easy_logger: ^0.0.2

  # Local Packages
  common:
    path: ./modules/common
  core:
    path: ./modules/core
  widgets:
    path: ./modules/widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  envied_generator: ^0.5.2
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
