name: flutter_movie_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0-95.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  auto_route: ^7.8.4

  # Serialization
  json_annotation: ^4.8.1
  equatable: ^2.0.5

  # State Management
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.4.9

  # Dependency Injection
  get_it: ^7.6.4

  # Network
  http: ^1.1.2

  # Localizations
  easy_localization: ^3.0.3

  # Utils
  envied: ^0.5.2
  kartal: ^3.5.0
  easy_logger: ^0.0.2

  # Local Packages
  common:
    path: ./modules/common
  core:
    path: ./modules/core
  widgets:
    path: ./modules/widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

  mockito: ^5.4.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  envied_generator: ^0.5.2

flutter:
  uses-material-design: true
